version: '3'
services:
  mso-mongo:
    image: mongo
    volumes:
      - /tmp/mso-mongo:/data/db
    command: mongod --port 27019
    ports:
      - "27019:27019"
  mso-api:
    build:
      context: ./../..
      dockerfile: docker/dev/Dockerfile.api
    image: mso-portal-api-dev
    environment:
      - NODE_ENV=development
      - NETWORK_MODE=false
      - PORT=3210
      - MONGO_URL=mongodb://mso-mongo:27019/mso-portal
    depends_on:
      - mso-mongo
    ports:
      - '3210:3210'

  mso-app:
    build:
      context: ./../..
      dockerfile: docker/dev/Dockerfile.app
    image: mso-portal-client-dev
    environment:
      - NODE_ENV=development
      - NETWORK_MODE=false
      - PORT=8081
      - MONGO_URL=mongodb://mso-mongo:27019/mso-portal
    depends_on:
      - mso-mongo
      - mso-api
    ports:
      - '8081:8081'

