FROM node:latest

# Development packages
RUN apt-get update;

# Create api directory
WORKDIR /usr/src/mso-portal

# Bundle api source
COPY . .
RUN ls -a

ENV MONGO_URL=mongodb://mongo:27017/mso-portal

RUN npm install

# Bundle app source
COPY . .

EXPOSE 3210
CMD [ "npm", "run", "start"]
