version: '3'
services:
  mongo:
    image: mongo
    volumes:
      - /tmp/mongodb:/data/db
    ports:
      - "27017:27017"
  api:
    build:
      context: ./../..
      dockerfile: docker/dev/Dockerfile.api
    image: mso-portal-api-dev
    network_mode: "host"
    environment:
      - NODE_ENV=development
      - PORT=3210
      - MONGO_URL=mongodb://127.0.0.1:27017/mso-portal
    depends_on:
      - mongo
#    volumes:
#      - ./../../api:/usr/src/api
    ports:
      - '3030:3030'

  app:
    build:
      context: ./../..
      dockerfile: docker/dev/Dockerfile.app
    image: mso-portal-client-dev
    network_mode: "host"
    environment:
      - NODE_ENV=development
      - PORT=8081
      - MONGO_URL=mongodb://127.0.0.1:27017/mso-portal
    depends_on:
      - mongo
      - api
#    volumes:
#      - ./../../app:/usr/src/app
    ports:
      - '8081:8081'

