version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    hostname: mongodb
    volumes:
      - /private/tmp/mongodb:/data/db

  mso-api:
    build:
      context: ./../..
      dockerfile: docker/dev/Dockerfile.api
    image: mso-portal-api-dev
    container_name: mso-api
    hostname: mso-api
    env_file:
               - ./../mso-config.env
    environment:
      - NODE_ENV=development
      - MSO_API_LISTEN_HOST=0.0.0.0
      - MSO_API_LISTEN_PORT=3210
      - MONGO_DB_URL=mongodb://mongodb/mso-portal
      - WEB_SOCKET_BASE_URL=${WEB_SOCKET_BASE_URL}
    depends_on:
      - mongodb
    ports:
      - '3210:3210'

  mso-app:
    build:
      context: ./../..
      dockerfile: docker/dev/Dockerfile.app
    image: mso-portal-client-dev
    container_name: mso-app
    hostname: mso-app
    env_file:
              - ./../mso-config.env
    environment:
      - NODE_ENV=development
      - MSO_APP_LISTEN_HOST=0.0.0.0
      - MSO_APP_LISTEN_PORT=8081
      - MONGO_DB_URL=mongodb://mongodb/mso-portal
    depends_on:
      - mongodb
      - mso-api
    ports:
      - '8081:8081'

networks:
  default:
   external:
         name: micronets-dev


